FROM rasa/rasa:2.0.3-full

COPY config_de.yml /app/config.yml
COPY credentials.yml /app/credentials.yml
COPY endpoints.yml /app/endpoints.yml
COPY projects/KI-Campus_de/* /app/projects/KI-Campus_de/
COPY projects/GreetBot_de/* /app/projects/GreetBot_de/


RUN rasa train --out /app/models

RUN rm /app/config.yml
RUN rm /app/credentials.yml
RUN rm /app/endpoints.yml
RUN rm -rf /app/projects/KI-Campus_de/
RUN rm -rf /app/projects/GreetBot_de/

ENTRYPOINT ["rasa"]