FROM rasa/rasa:2.0.3-full

COPY config_en.yml /app/config.yml
COPY credentials.yml /app/credentials.yml
COPY endpoints.yml /app/endpoints.yml
COPY projects/KI-Campus_en/* /app/projects/KI-Campus_en/
COPY projects/GreetBot_en/* /app/projects/GreetBot_en/


RUN rasa train --out /app/models

ENTRYPOINT ["rasa"]